version: "3"

services:
  src:
    container_name: xgTaxonomy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/xgTaxonomy/
    networks:
      - all

networks:
  all:
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/16